<a href="https://colab.research.google.com/github/ihyaulumuddin044/machineLearning/blob/main/regresi_menggunkan_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Regresi menggunkan KNN



In [1]:
# semple dataset
import pandas as pd

sensus = {
    "tinggi":[158, 170, 183, 191, 155, 163, 180,158,170],
    "berat":[64,86,84,80,49,59,67,54,67],
    "jk":['pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita'],
 }

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi  berat      jk
0     158     64    pria
1     170     86    pria
2     183     84    pria
3     191     80    pria
4     155     49  wanita
5     163     59  wanita
6     180     67  wanita
7     158     54  wanita
8     170     67  wanita

#membuat future dan target

In [2]:
import numpy as np
X_train = np.array(sensus_df[['tinggi','jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train:\n{X_train}\n')
print(f'y_train: {y_train}')


X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

y_train: [64 86 84 80 49 59 67 54 67]


#proses dataset: konversi label JK menjadi numerik

In [3]:
X_train_transposed = np.transpose(X_train)

print(f'X_train:\n{X_train}\n')
print(f'X_train_transposed:\n{X_train_transposed}')

X_train:
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

X_train_transposed:
[[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [4]:
# prosesing pelabelan untuk nilai binier
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print(f'jk: {X_train_transposed[1]}\n')
print(f'jk_binarised:\n{jk_binarised}')

jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised:
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [5]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [6]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print(f'X_train_transposed:\n{X_train_transposed}\n')
print(f'X_train:\n{X_train}')

X_train_transposed:
[[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]

X_train:
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


#melatih model dengan regression KNN

In [7]:
from sklearn.neighbors import KNeighborsRegressor

K = 3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

#presiksi berat badan

In [8]:
X_new = np.array([[170,0]])
X_new

array([[170,   0]])

In [9]:
y_pred = model.predict(X_new)
y_pred

array([70.66666667])

#evaluasi KNN regresion model

In [10]:
x_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

print(f'x_test:\n{x_test}\n')
print(f'y_test: {y_test}')

x_test:
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test: [65 96 52 67]


In [11]:
y_pred = model.predict(x_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])

#metrik Evluasi

>coefficien of determanition atau R²

In [12]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)

print(f'R-squared: {r_squared}')

R-squared: 0.6290565226735438


>Mean Absolute Error(MAE) atau Mean Absolute Deviation (MAD)

In [13]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_pred)

print(f'MAE: {MAE}')

MAE: 8.333333333333336


In [15]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)

print(f'MSE: {MSE}')

MSE: 95.8888888888889


#permasalahan scalling pada features

In [16]:
from scipy.spatial.distance import euclidean

# tinggin badan dalam milimeter
X_train = np.array([[1700,0],[1600,1]])
x_new = np.array([[1640,0]])

[euclidean( x_new[0], d) for d in X_train]

[60.0, 40.01249804748511]

In [17]:
# tinggu badan dalam cm
X_train = np.array([[1.7,0],[1.6,1]])
x_new = np.array([[1.64,0]])

[euclidean( x_new[0], d) for d in X_train]

[0.06000000000000005, 1.0007996802557442]