<a href="https://colab.research.google.com/github/ihyaulumuddin044/machineLearning/blob/main/simple_linier_regrresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

pizza = {"diameter": [6,8,10,14,18],
      "harga": [7,9,13,17.5,18]}

pizza_df = pd.DataFrame(pizza)
pizza_df
# pizza_df.shape

In [ ]:
import matplotlib.pyplot as plt

pizza_df.plot(x="diameter", y="harga", kind="scatter")
plt.title("perbandingan diameter dan harga pizza")
plt.xlabel("Diameter (inch)")
plt.ylabel("Price (dolar)")
plt.xlim(0,25)
plt.ylim(0,25)
plt.grid(True)
plt.show()

#penyesuian dataset

In [ ]:
import numpy as np

X = np.array(pizza_df["diameter"])
y = np.array(pizza_df["harga"])

print(f'X: {X}')
print(f'X: {y}')

In [ ]:
X = X.reshape(-1,1)
X.shape

In [ ]:
X

#training simlpe linier regression

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X,y)

LinearRegression()

#visulisasi simple linier regression

In [ ]:
X_vis = np.array([0,25]).reshape(-1,1)
y_vis = model.predict(X_vis)

In [ ]:
plt.scatter(X,y)
plt.plot(X_vis, y_vis, '-r')
plt.title("perbandingan diameter dan harga pizza")
plt.xlabel("Diameter (inch)")
plt.ylabel("Price (dolar)")
plt.xlim(0,25)
plt.ylim(0,25)
plt.grid(True)
plt.show

In [ ]:
print(f'intercept: {model.intercept_}')
print(f'slope: {model.coef_}')

#Mencari nilai Slope

In [14]:
print(f'x:\n{X}\n')
print(f'X flatten: {X.flatten()}\n')
print(f'y:\n{y}\n')

x:
[[ 6]
 [ 8]
 [10]
 [14]
 [18]]

X flatten: [ 6  8 10 14 18]

y:
[ 7.   9.  13.  17.5 18. ]



#menghitung nilai variance

In [15]:
variance_x = np.var(X.flatten(), ddof=1)
variance_x

23.2

#covariance

In [17]:
np.cov(X.flatten(), y)


array([[23.2 , 22.65],
       [22.65, 24.3 ]])

In [18]:
covariance_xy = np.cov(X.flatten(), y)[0][1]
covariance_xy

22.650000000000002

#slope

In [20]:
slope = covariance_xy / variance_x
print(f'slope: {slope}')

slope: 0.976293103448276


#Mencari nilai intercept

In [21]:
intersept = np.mean(y) - (slope * np.mean(X))
print(f'intersept: {intersept}')

intersept: 1.9655172413793096


#Prediksi harga pizza

In [22]:
diameter_pizza = np.array([12,20,23]).reshape(-1,1)
diameter_pizza

array([[12],
       [20],
       [23]])

In [24]:
prediksi_harga = model.predict(diameter_pizza)
prediksi_harga

array([13.68103448, 21.49137931, 24.42025862])

In [25]:
for dmtr, hrg in zip(diameter_pizza, prediksi_harga):
    print(f'diameter pizza: {dmtr}, prediksi harga: {hrg}')

diameter pizza: [12], prediksi harga: 13.681034482758621
diameter pizza: [20], prediksi harga: 21.491379310344826
diameter pizza: [23], prediksi harga: 24.42025862068965


#evaluasi simple linier regresion model

>training & testing

In [26]:
X_train = np.array([6,8,10,14,18]).reshape(-1,1)
y_train = np.array([7,9,13,17.5,18])
X_test = np.array([8,9,11,16,12]).reshape(-1,1)
y_test = np.array([11,8.5,15,18,11])

>training simple linier regression model

In [27]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

>evaluasi model

In [28]:
from sklearn.metrics import r2_score
y_pred = model.predict(X_test)
r_squared= r2_score(y_test, y_pred)
print(f'r_squared: {r_squared}')

r_squared: 0.6620052929422553


>mencari nilai R-squared

SSres

In [29]:
ss_res = sum([(y_i - model.predict(x_i.reshape(-1,1))[0])**2 for x_i, y_i in zip(X_test, y_test)])
print(f'ss_res: {ss_res}')

ss_res: 19.1980993608799


SStot

In [30]:
mean_y = np.mean(y_test)
ss_tot = sum([(y_i - mean_y)**2 for y_i in y_test])
print(f'ss_tot: {ss_tot}')

ss_tot: 56.8


R-redual / R²

In [31]:
r_squared = 1 - (ss_res / ss_tot)
print(f'r_squared: {r_squared}')

r_squared: 0.6620052929422553
